version: '3.7'

services:
  database:
    image: mysql:8.0
    command:
      - '--default-authentication-plugin=mysql_native_password'
    environment:
        - MYSQL_RANDOM_ROOT_PASSWORD=yes
        - MYSQL_DATABASE=codetest
        - MYSQL_USER=codetest
        - MYSQL_PASSWORD=swordfish
    ports:
      - "13306:3306"
    restart: always

  solution :
    image: solution
    build: images/solution
    volumes:
      - ./data:/data

